import type { NextPage } from 'next'
import Head from 'next/head';
import Link from 'next/link';
import Layout from '../components/layout';

import { mockBlogs } from '../data/mocks/mockBlogs';

const Home: NextPage = ({ blogs }: any) => {
  return (
    <Layout>
      <Head>
        <title>NextJS App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta property='og:title' content="NextJS App" />
        <meta property='og:description' content="Generated by create next app" />
        <meta property='og:image' content='/images/1.jpg' />
        <meta property='og:keyword' content='key,word' /> 
      </Head>
      <main>

        <h1>This is homepage </h1>
        {
          blogs.map(({ id, title, content }: any) =>(
            <div>
              <p><Link href={ '/posts/' + id }>{ title }</Link></p>
              { content }
            </div>
          ))
        }
      </main>
    </Layout>
  )
}

export async function getStaticProps(){
  console.log("mockBlogs: ", mockBlogs);
  let blogs : any  = mockBlogs;
  console.log("blogs: ", blogs);
  return {
    props: {
       
    }
  }
}

export default Home
