import type { GetServerSideProps, GetStaticProps, NextPage } from 'next'
import Head from 'next/head';
import Link from 'next/link'; 
import { mockBlogs } from '../data/mocks/mockBlogs';
import LayoutHome from '../layouts/layout-home/layout-home';

const Home: NextPage = ({ blogs }: any ) => {
  return (
    <> 
      <Head>
        <title>NextJS App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta property='og:title' content="NextJS App" />
        <meta property='og:description' content="Generated by create next app" />
        <meta property='og:image' content='/images/1.jpg' />
        <meta property='og:keyword' content='key,word' /> 
      </Head>
      <LayoutHome>
      <p>Index Page</p>
      </LayoutHome>
    </>
  )
}
/** Fetch data at build time */
export const getStaticProps: GetStaticProps = async (context) => {
  return {
    props: {
      blogs: JSON.parse(JSON.stringify(mockBlogs))
    }
  }
}
/** Fetch data at request time */
/*export const getServerSideProps: GetServerSideProps = async (context) => {
  return {
    props: {
      blogs: JSON.parse(JSON.stringify(mockBlogs))
    }
  }
}*/
export default Home
