import Link from 'next/link';
import Image from 'next/image';
import Head from 'next/head';
import Script from 'next/script';
import Layout from '../../components/layout';

export default function FirstPost(){
    return (
        <Layout>
            <Head>
                <title>First Post</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta property='og:title' content="First Post" />
                <meta property='og:description' content="Generated by create next app" />
                <meta property='og:image' content='/images/1.jpg' />
                <meta property='og:keyword' content='first,post' /> 
            </Head>
            <Script src="https://connect.facebook.net/en_US/sdk.js" strategy='lazyOnload' onLoad={() => console.log('FB script loaded')} />
            <h1>First Post</h1>
            <Image src='/images/1.jpg' alt="1" height={360} width={540}/>
            <h2><Link href="/">Back to home</Link></h2>
        </Layout>
    )
}